name: Build OSM2Map

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build OSM2Map"

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: recursive

      - name: Setup Java SDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: "microsoft"
          cache: "gradle"

      - name: Grant Write Permissions to gradlew script
        run: chmod 700 ./gradlew

      - name: Build
        run: ./gradlew build -Xlint:deprecation